spring.application.name=Payment-Integration
server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/payment_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



razorpay.key.id=rzp_test_SJGOqk1B4bqcdH
razorpay.key.secret=3aXNV0pANS2wMFx72T1kG0il
