
# STEP :1  Basic Workflow Start
name: Payment-app
on: 
 push:
   branches: 
     - main
     
# Step 2 — Job Create Karna
jobs:
  build:
    runs-on: ubuntu-24.04
    
# Step 3 — Code Download Step
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
# Step 4 — Java Setup
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        
# Step 5 — Project Build (JAR)
    - name: Build Jar
      run: mvn clean package -DskipTests

# Step 6 — JAR EC2 par Copy Karna
    - name: Copy jar to EC2
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USER }}
       key: ${{ secrets.EC2_KEY }}
       source: "target/*.jar"
       target: "/home/ubuntu/"
      
   # Step 7 — EC2 par JAR Run Karna

    - name: Run jar on EC2
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USER }}
       key: ${{ secrets.EC2_KEY }}
       script: |
        pkill -f 'java -jar' || true
        nohup java -jar /home/ubuntu/*.jar > app.log 2>&1 &
   
    
